apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopsphere.fullname" . }}-secrets
  labels:
    {{- include "shopsphere.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "postgres://user:pass@localhost:5432/db" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | default "default-jwt-secret-key" | quote }}
  PAYMENT_GATEWAY_KEY: {{ .Values.secrets.paymentGatewayKey | default "pk_dummy_gateway_key" | quote }}
  ADMIN_API_KEY: {{ .Values.secrets.adminApiKey | default "adm_dummy_default" | quote }}
