apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopsphere-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/shopsphere-helm-project.git'
    targetRevision: main
    path: argocd
    directory:
      recurse: false
      exclude: 'root-app.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
